version: "3"
services:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - 4000:4000
  links:
    - prisma
    - sql

  prisma:
    image: prismagraphql/prisma: prismagraphql/prisma:1.13
    ports:
      - '4466:4466'
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  
            migrations: true
            host: mysql
            port: 3306        
            user: root
            password: prisma

  sql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - 3306:3306