version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/backend/src
      - ./prisma:/backend/prisma
    ports:
      - 4000:4000
    env_file:
      - ./.env
    # command: "npm run prod"
    links:
      - mysql
      - prisma

  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  
            migrations: true
            host: mysql
            port: 3306  
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
