version: "3"
services:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - 4000:4000
  volumes:
    - .:/app:cached
    - node_modules:/app/node_modules
    - public:/app/server/src/public
    - build:/app/server/build
    # - client_node_modules:/app/client/node_modules
    # - server_node_modules:/app/server/node_modules
  links:
    - prisma
    - sql

  prisma:
    image: prismagraphql/prisma: prismagraphql/prisma:1.13
    ports:
      - '4466:4466'
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  
            migrations: true
            host: mysql
            port: 3306        
            user: root
            password: prisma

  mysql-server:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - 3306:3306